### ISSUE TITLE
It’s ready?

### ISSUE THREAD

**Issue by Alexey-T** [ildarkhasanshin/cuda_folding_caption#1]
Судя по коду он показывает то же что и FoldRuler. Тогда тоже рано публиковать. Надо чтобы он для некоторых основных лексеров показывал верное инфо . Например С Cpp Python PHP . Я уже писал про это. Пока это игрушка

**Comment by ildarkhasanshin** [comment]
да, пока что показывает то же самое
главное предназначение этого функционала - вывод вложенности и быстрый переход к разным уровням

в pycharm так
![image](https://user-images.githubusercontent.com/8765305/224495372-484c1233-3d33-4f73-974d-256e389c7665.png)

**Comment by Alexey-T** [comment]
вот то что на скрине внизу-- у нас тоже есть. Breadcrumbs. там по опции - дает цепочку по code tree.

**Comment by Alexey-T** [comment]
тогда если это есть в Breadcr, нужен ли плагин?

**Comment by ildarkhasanshin** [comment]
> там по опции - дает цепочку по code tree

не нашел

![image](https://user-images.githubusercontent.com/8765305/224496049-b6928702-1b9c-47dd-9a11-cec0d41a2ad7.png)
это имеется ввиду?
но здесь не вся цепочка в сравнении с pycharm

**Comment by Alexey-T** [comment]
имеется в виду что если опцию заюзать, то Breadcr покажет узлы code tree в нижней цепочке. даже без вызова code tree менюшки.

**Comment by Alexey-T** [comment]
![b](https://user-images.githubusercontent.com/4154978/224496259-253cdebd-7a65-4ec2-94eb-8e51ae507b5c.png)

**Comment by ildarkhasanshin** [comment]
но там все равно только основные уровни выводятся?

**Comment by Alexey-T** [comment]
да, выводится  пункты которые есть в code tree. без 'if', 'try'.

**Comment by ildarkhasanshin** [comment]
когда много кода в блоках if, try, .. для наглядности хорошо бы и их выводить
как в pycharm

**Comment by Alexey-T** [comment]
Ok
