### ISSUE TITLE
2 Go-to commands must check first, is editor lexer supported

### ISSUE THREAD

**Issue by Alexey-T** [ildarkhasanshin/cuda_folding_caption#15]

**Comment by ildarkhasanshin** [comment]
можно подробнее?

**Comment by Alexey-T** [comment]
В командах go to , надо проверить сначала , контролируется ли текущий редактор плагином , и виден ли статусбар. И если да то прыгать .

**Comment by ildarkhasanshin** [comment]
вроде только проверки `len(self.lines_)` достаточно
