### ISSUE TITLE
Cud crashes when I reopen python file

### ISSUE THREAD

**Issue by Alexey-T** [ildarkhasanshin/cuda_folding_caption#18]
`ERROR: Exception in CudaText for on_caret_slow: Access violation`

падает в statusbar_proc() с ошибочным хендлом - по этому хендлу не получить обьект. видимо обьект уже был удален а плагин помнит старый хендл (= ссылка на обьект в памяти).

повтор

- открываем файл питона 
[test.zip](https://github.com/ildarkhasanshin/cuda_folding_caption/files/11049318/test.zip)
- идем на строку 4617
- закроем файл крестиком на табе
- вызовем тот же файл из recent files -> crash

**Comment by Alexey-T** [comment]
можно уследить когда редактор поменялся - по хендлу `ed_self.h`. видимо и статусбар надо заново создать?

**Comment by veksha** [comment]
@ildarkhasanshin @Alexey-T please see PR.
