### ISSUE TITLE
maybe, not sure - add option to allow bar placed on the bottom

### ISSUE THREAD

**Issue by Alexey-T** [ildarkhasanshin/cuda_folding_caption#4]
```
dlg_proc(self.h_pf, DLG_CTL_PROP_SET, index=self.n_sbf, prop={'align':ALIGN_TOP})
```
ALIGN_BOTTOM is good for some users.

**Comment by ildarkhasanshin** [comment]
STATUSBAR_SET_CELL_COLOR_LINE/STATUSBAR_SET_CELL_COLOR_LINE2
как настроить высоту линий?

**Comment by Alexey-T** [comment]
линии подстраиваются под статусбар. Можно его высоту поменять. Dlg_proc.

**Comment by ildarkhasanshin** [comment]
![image](https://user-images.githubusercontent.com/8765305/226316292-c6ab0b9f-5baa-4624-a2bd-bae8536460e3.png)

имею ввиду, линию внизу

**Comment by Alexey-T** [comment]
там  4 пикселя. без опций.
