### ISSUE TITLE
truncation of long function name

### ISSUE THREAD

**Issue by Alexey-T** [ildarkhasanshin/cuda_folding_caption#8]
ячейка статусбара отсекает половину имени. так и надо?

![Screenshot from 2023-03-21 19-53-22](https://user-images.githubusercontent.com/4154978/226683942-97be0f7f-c06f-481f-9c36-88ffdc6e8202.png)

**Comment by Alexey-T** [comment]
если так и надо - то прошу опцию "cell_width".

**Comment by ildarkhasanshin** [comment]
STATUSBAR_SET_CELL_AUTOSIZE
